osx_image: xcode12.2
language: c

compiler:
  - gcc
  - clang
homebrew:
    packages:
      - libftdi
      - hidapi
    update: true
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    
script: true
