os: osx
osx_image: xcode12.2
language: c
addons:
    homebrew:
        packages:
            - libftdi
            - hidapi
        update: true
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    
script:
    - echo done
